### PR TITLE
Move formulae into a dedicated directory

### PR DESCRIPTION
**Pull request by xgarrido**
Following recommendations from this wiki
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md
formulae are moved into a special and dedicated directory to avoid mix

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Looks fine, but let's resolve the Issue #6 first

**Comment by xgarrido** [comment]
I have merged your recent changes to `root5` formula.

**Comment by xgarrido** [comment]
Ok I did some shitty stuff with my `master` branch and I didn't want to include the `CLHEP` patch into this pull request. Feel free to catch what you want (`git rebase` is too complicated for me...)

**Comment by drbenmorgan** [comment]
I have moved the formula to a dedicated directory without the other patches which can be merged in separately as needed.

**Pull request closed without merging**
